name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ./backend/target/**
          key: backend-build-rustmine

      - name: Install Dependencies
        run: |
          yarn
          cd backend && yarn

      - name: Build Backend
        run: |
          yarn compile-backend
