name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
     
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          yarn
          cd backend && yarn

      # Runs a set of commands using the runners shell
      - name: Build Backend
        run: |
          yarn compile-backend
